language: python

python:
  - '2.6'
  - '2.7'
  - '3.3'

before_install:
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - pip install --upgrade twitter
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov

script: py.test --cov pyweet -rf -v

after_success:
  - coveralls

notifications:
  irc:
    channels: irc.freenode.org#atal-dev
    on_success: change
    on_failure: change

env:
  global:
    secure: "SeKb0zZ/gv9SZd5WIziL54BZz0YczpV+OIMmuzgK9eaJq6hmHWRJ4VZa2c5Xkx3YoVl/Y6CkIu1zL3WBm/IaajkuUCyrQhWrTZzxJJtDOPyQWO9EqE7r6kTWuqYOOXDp2EDxvQoE0bbrsJ9EsXLGw5FgC0AOc43Cvoh3hlm1gG4="
