language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

before_install:
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - pip install --upgrade twitter
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov

script: py.test --cov pyweet

after_success:
  - coveralls

notifications:
  irc:
    channels: irc.freenode.org#atal-dev
    on_success: change
    on_failure: change

env:
  global:
    secure: "hmPyUXW28BMvYksWnVgz7WED9klFuTU9JkB/c3iZtf0SX00HE5i1pp55rHkrdHxT9jyKOdUv6PBP+teuOW602kppjfdFGQWdD6MqYGABZ7I8FNyj8bgqMslTbO4DlmK6k02wV2FlIFgQ7JnbIE8KeNbEmghbcd/wjefprMqt94k="
