language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

before_install:
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' || $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install --upgrade futures; fi

script: "nosetests --with-coverage --cover-package=pyweet"

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
